// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void TurnOn(lv_event_t * e);
void TurnOff(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
