// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_BackgroundImage;
lv_obj_t * ui_TempLabel;
lv_obj_t * ui_HumiLabel;
void ui_event_OnButton(lv_event_t * e);
lv_obj_t * ui_OnButton;
void ui_event_OffButton(lv_event_t * e);
lv_obj_t * ui_OffButton;
// CUSTOM VARIABLES

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_OnButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TurnOn(e);
    }
}

void ui_event_OffButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        TurnOff(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_display_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_display_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    lv_screen_load(ui_Screen1);
}
