// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

// Shares the requested output state with the main PlatformIO loop.
extern int led;
extern int charge_mode_request;
extern int set_current_request;

/*---------------------------------------------------------------
 * Handle dashboard commands
 * Keep generated UI events separate from hardware output updates.
 *--------------------------------------------------------------*/

/**
 * @brief Request the controlled output to turn on.
 * @param e LVGL event that triggered the command; not inspected here.
 * @return Nothing.
 * @note Called after ui_OnButton receives LV_EVENT_RELEASED.
 */
void TurnOn(lv_event_t * e)
{
    (void)e;
    led = 1;
}

/**
 * @brief Request the controlled output to turn off.
 * @param e LVGL event that triggered the command; not inspected here.
 * @return Nothing.
 * @note Called after ui_OffButton receives LV_EVENT_RELEASED.
 */
void TurnOff(lv_event_t * e)
{
    (void)e;
    led = 0;
}

/**
 * Request a Wallbox operating mode.
 * The request is shown as pending until MQTT state feedback confirms it.
 */
void SelectManualMode(lv_event_t * e)
{
    (void)e;
    charge_mode_request = 0;
}

void SelectAutoMode(lv_event_t * e)
{
    (void)e;
    charge_mode_request = 1;
}

void SelectScheduledMode(lv_event_t * e)
{
    (void)e;
    charge_mode_request = 2;
}

/**
 * Request the selected manual-mode charging current.
 * The slider value is published only after the user releases it.
 */
void SetChargeCurrent(lv_event_t * e)
{
    lv_obj_t *slider = (lv_obj_t *)lv_event_get_target(e);
    set_current_request = (int)lv_slider_get_value(slider);
}
