// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: Basic_LVGL_7-5

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BackgroundImage = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_BackgroundImage, &ui_img_background_png);
    lv_obj_set_width(ui_BackgroundImage, LV_SIZE_CONTENT);   /// 800
    lv_obj_set_height(ui_BackgroundImage, LV_SIZE_CONTENT);    /// 480
    lv_obj_set_align(ui_BackgroundImage, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BackgroundImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BackgroundImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, -50);
    lv_obj_set_y(ui_TempLabel, -100);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "25");
    lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumiLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumiLabel, -50);
    lv_obj_set_y(ui_HumiLabel, 50);
    lv_obj_set_align(ui_HumiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumiLabel, "50");
    lv_obj_set_style_text_font(ui_HumiLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OnButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_OnButton, 100);
    lv_obj_set_height(ui_OnButton, 100);
    lv_obj_set_x(ui_OnButton, 260);
    lv_obj_set_y(ui_OnButton, -100);
    lv_obj_set_align(ui_OnButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OnButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OnButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OnButton, lv_color_hex(0x2061CD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OnButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_OnButton, &ui_img_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OffButton = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_OffButton, 100);
    lv_obj_set_height(ui_OffButton, 100);
    lv_obj_set_x(ui_OffButton, 260);
    lv_obj_set_y(ui_OffButton, 50);
    lv_obj_set_align(ui_OffButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OffButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OffButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OffButton, lv_color_hex(0x735DDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OffButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_OffButton, &ui_img_off_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_OnButton, ui_event_OnButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OffButton, ui_event_OffButton, LV_EVENT_ALL, NULL);

}
